version: 2.1
orbs:
  kubernetes: circleci/kubernetes@1.3.1

# Pipeline parameters
parameters:
  ondemand:
    type: boolean
    default: false
  deployment:
    type: string
    default: "invalid deployment"
  container:
    type: string
    default: "invalid container"
  image:
      type: string
      default: "invalid image"
  namespace:
      type: string
      default: "default"

jobs:
  deploy-manifests:
    docker:
      - image: cimg/base:current
    resource_class: project-buildspace/circleci
    steps:
      - checkout

      - kubernetes/install-kubeconfig:
          kubeconfig: _KUBECONFIG

      - kubernetes/install-kubectl

      - run:
          name: Create tmp directory
          command: mkdir tmp

      - run:
          name: echo $CIRCLE_KUBECONFIG
          command: echo $CIRCLE_KUBECONFIG

           
      - run:
          name: Copy yamls to tmp
          command: find "yamls" -type f -name "*.y*ml" -exec cp {} tmp/ \;
           
      - run:
          name: List tmp
          command: ls tmp;

      - kubernetes/create-or-update-resource:
          resource-file-path: "tmp"

      - run:
          name: Delete tmp
          command: rm -rf tmp
    
  update-resources:
    docker:
      - image: cimg/base:current
    resource_class: project-buildspace/circleci
    steps:
      - kubernetes/install-kubeconfig:
          kubeconfig: _KUBECONFIG

      - kubernetes/install-kubectl

      - kubernetes/update-container-image:
          container-image-updates: << pipeline.parameters.container >>=<< pipeline.parameters.image >>
          resource-name: deployment/<< pipeline.parameters.deployment >>
          namespace: << pipeline.parameters.namespace >>
          show-kubectl-command: true

workflows:
  build-workflow:
    unless: << pipeline.parameters.ondemand >>
    jobs:
      - deploy-manifests

  workflow-job2-ondemand:
    when: << pipeline.parameters.ondemand >>
    jobs:
      - update-resources