version: 2.1
orbs:
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  deploy-manifests:
    docker:
      - image: cimg/base:current
    resource_class: project-buildspace/circleci
    steps:
      - checkout

      - kubernetes/install-kubeconfig:
          kubeconfig: KUBECONFIG

      - kubernetes/install-kubectl

      - run:
          name: Create tmp directory
          command: mkdir tmp
           
      - run:
          name: Copy yamls to tmp
          command: find "yamls" -type f -name "*.y*ml" -exec cp {} tmp/ \;
           
      - run:
          name: List tmp
          command: ls tmp;

      - kubernetes/create-or-update-resource:
          resource-file-path: "tmp"
          envsubst: true

      - run:
          name: Delete tmp
          command: rm -rf tmp

workflows:
  build-workflow:
    jobs:
      - deploy-manifests
