apiVersion: v1
kind: Namespace
metadata:
  name: oidc
---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-secret
  namespace: oidc
data:
  username: YnVpbGRzcGFjZQ==
  password: NEA4PGxrNDxpQWhwJm9m
---
apiVersion: v1
kind: Secret
metadata:
  name: picture-keys
  namespace: oidc
data:
  accessKey: M2VMc1BYMExuYzNQcXV4TVJvTEY=
  secretAccessKey: RkNadTNYVGJyVkxLdng5eHJab1FqaG5KeHBvVUlMNktnTXdVblNieg==
---