apiVersion: v1
kind: Namespace
metadata:
  name: oidc
---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-secret
  namespace: oidc
data:
  username: YnVpbGRzcGFjZQ==
  password: NEA4PGxrNDxpQWhwJm9m