# psql -W keycloak -U buildspace
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: oidc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-oidc
  namespace: oidc
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres-oidc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-oidc
  namespace: oidc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-oidc
  template:
    metadata:
      labels:
        app: postgres-oidc
    spec:
      containers:
        - name: postgres-oidc
          image: postgres:12-alpine
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oidc-secret
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: oidc-secret
                  key: username
            - name: POSTGRES_DB
              value: "keycloak"
          volumeMounts:
            - name: postgres-oidc-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-oidc-data
          persistentVolumeClaim:
            claimName: oidc-postgres
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: oidc-postgres
  namespace: oidc
spec:
  storageClassName: slow
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/data"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oidc-postgres
  namespace: oidc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: slow
  resources:
    requests:
      storage: 4Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: buildspace-realm
  namespace: oidc
spec:
  storageClassName: slow
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/yamls/0-OIDC/realms/buildspace-realm.json"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildspace-realm-pvc
  namespace: oidc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: slow
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: oidc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycoak
          image:  jboss/keycloak
          args: ["-Dkeycloak.profile.feature.scripts=enabled","-Dkeycloak.profile.feature.upload_scripts=enabled"] #"-Dkeycloak.import=/realms/buildspace-realm.json"
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_VENDOR
              value: "postgres"
            - name: DB_ADDR
              value: "postgres-oidc"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "keycloak"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: KEYCLOAK_FRONTEND_URL
              value: "https://keycloak-buildspace.euinno.eu/auth/"
#            - name: KC_TRANSACTION_XA_ENABLED
#              value: "false"
#            - name: KC_PROXY
#              value: "edge"
            # - name: HTTPS_TRUST_STORE_FILE
            #   value: truststore.p12
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: oidc-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oidc-secret
                  key: password
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: oidc-secret
                  key: username
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oidc-secret
                  key: password
          volumeMounts:
            - name: buildspace-realm
              mountPath: /yamls/0-OIDC/realms
      volumes:
        - name: buildspace-realm
          persistentVolumeClaim:
            claimName: buildspace-realm-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: oidc
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: https
      nodePort: 30105
      targetPort: 8080
  selector:
    app: keycloak
  type: NodePort
---