apiVersion: v1
kind: Secret
metadata:
  name: admin-user
  namespace: oidc
data:
  username: YnVpbGRzcGFjZQ==
  password: NEA4PGxrNDxpQWhwJm9m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-manager-api
  namespace: oidc
  labels:
    app: account-manager-api
spec:
  replicas: 1
  template:
    metadata:
      name: account-manager-api
      labels:
        app: account-manager-api
    spec:
      containers:
        - name: account-manager-api
          image: buildspace/account-manager-api
          ports:
            - containerPort: 5000
          env:
          - name: ADMIN_UNAME
            valueFrom:
              secretKeyRef:
                name: admin-user
                key: username
          - name: ADMIN_PWD
            valueFrom:
              secretKeyRef:
                name: admin-user
                key: password
          - name: ADMIN_CLIENT
            value: admin-cli
          - name: REALM
            value: buildspace
          - name: ISSUER
#            value: "keycloak.oidc:8080/auth"
            value: "https://keycloak-dataspaces.euinno.eu/auth"
          - name: BS_CERTS
            value: "/realms/buildspace/protocol/openid-connect/certs"
          - name: DEBUG
            value: "false"
      restartPolicy: Always
  selector:
    matchLabels:
      app: account-manager-api
---
kind: Service
apiVersion: v1
metadata:
  name: account-manager-api
  namespace: oidc
spec:
  selector:
    app: account-manager-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
---