apiVersion: v1
kind: Secret
metadata:
  name: admin-user
  namespace: oidc
data:
  username: YnVpbGRzcGFjZQ==
  password: NEA4PGxrNDxpQWhwJm9m
---
apiVersion: v1
kind: Secret
metadata:
  name: kc-client
  namespace: oidc
data:
  id: bWluaW9hcGk=
  secret: Yzlqemc4MElIRWVsUnNJODUwRWZsZ3FxbU15U3V3V2U=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-manager-api
  namespace: oidc
  labels:
    app: account-manager-api
spec:
  replicas: 1
  template:
    metadata:
      name: account-manager-api
      labels:
        app: account-manager-api
    spec:
      containers:
        - name: account-manager-api
          image: buildspace/account-manager-api
          ports:
            - containerPort: 5000
          env:
          - name: ADMIN_UNAME
            valueFrom:
              secretKeyRef:
                name: admin-user
                key: username
          - name: ADMIN_PWD
            valueFrom:
              secretKeyRef:
                name: admin-user
                key: password
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: kc-client
                key: id
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: kc-client
                key: secret
          - name: ADMIN_CLIENT
            value: admin-cli
          - name: REALM
            value: buildspace
          - name: ISSUER
#            value: "keycloak.oidc:8080/auth"
            value: "https://keycloak-buildspace.euinno.eu/auth"
          - name: BS_CERTS
            value: "/realms/buildspace/protocol/openid-connect/certs"
          - name: DEBUG
            value: "false"
            # For Pictures
          - name: USER_DEFAULT_PICTURE
            value: default_user_icon.png
          - name: COPERNICUS_BUCKET_ID
            value: 1ae79ed4-b1c0-49fb-a762-ed289663fa2c
          - name: STORAGE
            value: minioapi-buildspace.euinno.eu
          - name: PICTURES_BUCKET_ENDPOINT
            value: pictures
          - name: ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: picture-keys
                key: accessKey
          - name: SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: picture-keys
                key: secretAccessKey

      restartPolicy: Always
  selector:
    matchLabels:
      app: account-manager-api
---
kind: Service
apiVersion: v1
metadata:
  name: account-manager-api
  namespace: oidc
spec:
  selector:
    app: account-manager-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
---