---
apiVersion: v1
kind: Secret
metadata:
  name: minio-keys
  namespace: buildspace-storage
data:
  accessKey: c2E1REdZVkdpNDVGUTlKZVJyZkE=
  secretAccessKey: UnN5UW9JOFRGd0FDak9Zak5NdE1vbHg0bGR4VmdWME92cTlNaTluUw==
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-client
  namespace: buildspace-storage
data:
  id: bWluaW9hcGk=
  password: Yzlqemc4MElIRWVsUnNJODUwRWZsZ3FxbU15U3V3V2U=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-api-app
  namespace: buildspace-storage
  labels:
    app: storage-api-app
spec:
  replicas: 3
  template:
    metadata:
      name: storage-api-app
      labels:
        app: storage-api-app
    spec:
      containers:
        - name: storage-api
          image: buildspace/storage-api
          ports:
            - containerPort: 8006
#          imagePullPolicy: IfNotPresent
          env:
          - name: ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-keys
                key: accessKey
          - name: SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-keys
                key: secretAccessKey
          - name: DATABASE
            value: minio
          - name: MONGO_URL
            value: mongodb://mongodb-service.buildspace-storage:27017
          - name: MINIO_URL
            value: minio.buildspace-storage:9000
          - name: OIDC_PROVIDER
            value: https://keycloak-buildspace.euinno.eu/auth/realms/buildspace
          - name: COP_BUCKET_ID
            value: 1ae79ed4-b1c0-49fb-a762-ed289663fa2c
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: minio-client
                key: id
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: minio-client
                key: password
          - name: ADS_UID
            valueFrom:
              secretKeyRef:
                name: secret-ads
                key: UUID
          - name: ADS_KEY
            valueFrom:
              secretKeyRef:
                name: secret-ads
                key: key
          - name: CDS_UID
            valueFrom:
              secretKeyRef:
                name: secret-cds
                key: UUID
          - name: CDS_KEY
            valueFrom:
              secretKeyRef:
                name: secret-cds
                key: key
      restartPolicy: Always
  selector:
    matchLabels:
      app: storage-api-app
---
kind: Service
apiVersion: v1
metadata:
  name: storage-api
  namespace: buildspace-storage
spec:
  selector:
    app: storage-api-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 30000
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: storage-api-service
#  namespace: buildspace-storage
#spec:
#  selector:
#    app: storage-api-app
#  ports:
#    - protocol: TCP
#      port: 8006
#      targetPort: 8006
#  type: NodePort
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: storage-api-service
#  namespace: buildspace-storage
#spec:
#  selector:
#    app: storage-api-app
#  ports:
#    - port: 8006
#      name: api
#  type: ClusterIP